name: Deploy to Replit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test || echo "Tests skipped"
    
    - name: Build application
      run: npm run build
      
    - name: Build static version
      run: npm run build:static || echo "Static build skipped"
    
    - name: Deploy to Replit
      run: echo "Deploy to Replit via webhook or API"
      # TODO: Add Replit deployment webhook
